[package]
name = "recto-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
image.workspace = true
kamadak-exif.workspace = true
rayon.workspace = true
tempfile.workspace = true
pdf-writer.workspace = true
dirs.workspace = true
async-channel.workspace = true

opencv = { version = "0.98", default-features = false, features = ["imgproc", "imgcodecs"] }
